services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  ingest:
    build: 
      context: .
      dockerfile: services/ingest/Dockerfile
    volumes:
      - ./services/ingest:/app
      - ./libs:/libs
    environment:
      - INGEST_PORT=8000
      - OPENAI_API_KEY= "${OPENAI_API_KEY}"
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
  graph:
    build:
      context: .
      dockerfile: services/graph/Dockerfile
    volumes:
      - ./services/graph:/app
      - ./libs:/libs
    environment:
      - GRAPH_PORT=8001
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8001:8001"
  analysis:
    build:
      context: .
      dockerfile: services/analysis/Dockerfile
    volumes:
      - ./services/analysis:/app
      - ./libs:/libs
    environment:
      - ANALYSIS_PORT=8002
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8002:8002"
