services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  ingest:
    build: 
      context: .
      dockerfile: services/ingest/Dockerfile
    volumes:
      - ./services/ingest:/app
      - ./libs:/libs
    environment:
      - INGEST_PORT=8000
      - OPENAI_API_KEY= "${OPENAI_API_KEY}"
      - KAFKA_BOOTSTRAP=kafka:9092
    ports:
      - "8000:8000"
  graph:
    build:
      context: .
      dockerfile: services/graph/Dockerfile
    volumes:
      - ./services/graph:/app
      - ./libs:/libs
    environment:
      - GRAPH_PORT=8001
      - KAFKA_BOOTSTRAP=kafka:9092
    ports:
      - "8001:8001"
  analysis:
    build:
      context: .
      dockerfile: services/analysis/Dockerfile
    volumes:
      - ./services/analysis:/app
      - ./libs:/libs
    environment:
      - ANALYSIS_PORT=8002
      - KAFKA_BOOTSTRAP=kafka:9092
    ports:
      - "8002:8002"