version: '3.8'
services:
  ingest:
    build: ./services/ingest
    volumes:
      - ./services/ingest:/app
      - ./libs:/libs
    environment:
      - INGEST_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy}
    ports:
      - "8000:8000"

